import Link from 'next/link';
import './globals.css';

export const metadata = {
  title: 'Next Js Movies App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={' mx-32 my-12'}>
        <header className="h-20 sticky top-0 shadow-lg">
          <div className="text-2xl">
            <Link href={'#home'}>Movies App 🎞</Link>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
